# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05efe4aca3d3599e9161addcd9bf18a9f5632247b8ba00d77e38566d4e4d6d7069a99e3096fe91a9c48260135cbb0ba0273886a5818aceb33e44d3374b3983be

test:
  secret_key_base: 70eb1d36a25278406c4d4421d81e94caf780649bd7dfc0d60ebcf816cc4238f95715b56eb92a6010aae58bbb43c55965d578a009bfdac23e15bdf5d9a0c90c17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
